/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.StudentUI;

/**
 *
 * @author hotua
 */
public class ProfileStudent extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    public ProfileStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPChuaThongTin = new javax.swing.JPanel();
        jpThongTin1 = new javax.swing.JPanel();
        jlbTen = new javax.swing.JLabel();
        tfTen = new javax.swing.JTextField();
        lbKhoa = new javax.swing.JLabel();
        tfKhoa = new javax.swing.JTextField();
        lbDay = new javax.swing.JLabel();
        tfDay = new javax.swing.JTextField();
        lbNoiSinh = new javax.swing.JLabel();
        tfNoiSinh = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbGioiTinh = new javax.swing.JLabel();
        tfGioiTinh = new javax.swing.JTextField();
        lbChuongTrinh = new javax.swing.JLabel();
        tfChuongTrinh = new javax.swing.JTextField();
        jPChuaThongTin2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lbLop = new javax.swing.JLabel();
        lbNganh = new javax.swing.JLabel();
        tfNganh = new javax.swing.JTextField();
        lbCCCD = new javax.swing.JLabel();
        tfCCCD = new javax.swing.JTextField();
        lbCCCD1 = new javax.swing.JLabel();
        tfDanToc = new javax.swing.JTextField();
        lbQuocTich = new javax.swing.JLabel();
        tfQuocTich = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        lbSDT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(175, 202, 250));

        jPChuaThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)), "Thông Tin Chung", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(0, 153, 255))); // NOI18N
        jPChuaThongTin.setForeground(new java.awt.Color(255, 255, 255));
        jPChuaThongTin.setLayout(new java.awt.GridLayout(1, 0));

        jlbTen.setText("Họ và Tên:");
        jlbTen.setVerifyInputWhenFocusTarget(false);

        tfTen.setEditable(false);

        lbKhoa.setText("Khoa:");

        tfKhoa.setEditable(false);

        lbDay.setText("Ngày sinh:");

        tfDay.setEditable(false);

        lbNoiSinh.setText("Nơi sinh:");

        tfNoiSinh.setEditable(false);

        lbEmail.setText("Email:");

        tfEmail.setEditable(false);

        lbGioiTinh.setText("Giới Tính:");

        tfGioiTinh.setEditable(false);

        lbChuongTrinh.setText("Chương trình:");

        tfChuongTrinh.setEditable(false);

        javax.swing.GroupLayout jpThongTin1Layout = new javax.swing.GroupLayout(jpThongTin1);
        jpThongTin1.setLayout(jpThongTin1Layout);
        jpThongTin1Layout.setHorizontalGroup(
            jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNoiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbChuongTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNoiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(tfEmail)
                    .addComponent(tfTen)
                    .addComponent(tfKhoa)
                    .addComponent(tfGioiTinh)
                    .addComponent(tfChuongTrinh)
                    .addComponent(tfDay))
                .addContainerGap())
        );
        jpThongTin1Layout.setVerticalGroup(
            jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongTin1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTen)
                    .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKhoa))
                .addGap(18, 18, 18)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDay))
                .addGap(18, 18, 18)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNoiSinh))
                .addGap(18, 18, 18)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addGap(18, 18, 18)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGioiTinh))
                .addGap(18, 18, 18)
                .addGroup(jpThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbChuongTrinh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPChuaThongTin.add(jpThongTin1);

        jTextField1.setEditable(false);

        lbLop.setText("Lớp:");
        lbLop.setVerifyInputWhenFocusTarget(false);

        lbNganh.setText("Ngành:");
        lbNganh.setVerifyInputWhenFocusTarget(false);

        tfNganh.setEditable(false);

        lbCCCD.setText("Số CCCD:");
        lbCCCD.setVerifyInputWhenFocusTarget(false);

        tfCCCD.setEditable(false);

        lbCCCD1.setText("Dân Tộc:");
        lbCCCD1.setVerifyInputWhenFocusTarget(false);

        tfDanToc.setEditable(false);

        lbQuocTich.setText("Quốc Tịch:");
        lbQuocTich.setVerifyInputWhenFocusTarget(false);

        tfQuocTich.setEditable(false);

        tfSDT.setEditable(false);

        lbSDT.setText("SĐT:");
        lbSDT.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPChuaThongTin2Layout = new javax.swing.GroupLayout(jPChuaThongTin2);
        jPChuaThongTin2.setLayout(jPChuaThongTin2Layout);
        jPChuaThongTin2Layout.setHorizontalGroup(
            jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                        .addComponent(lbLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                        .addComponent(lbNganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                        .addComponent(lbCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                        .addComponent(lbCCCD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                        .addComponent(lbQuocTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                        .addComponent(lbSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPChuaThongTin2Layout.setVerticalGroup(
            jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPChuaThongTin2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLop))
                .addGap(18, 18, 18)
                .addGroup(jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNganh))
                .addGap(18, 18, 18)
                .addGroup(jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCCCD))
                .addGap(18, 18, 18)
                .addGroup(jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCCCD1))
                .addGap(18, 18, 18)
                .addGroup(jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuocTich))
                .addGap(18, 18, 18)
                .addGroup(jPChuaThongTin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSDT))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jPChuaThongTin.add(jPChuaThongTin2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPChuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPChuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPChuaThongTin;
    private javax.swing.JPanel jPChuaThongTin2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlbTen;
    private javax.swing.JPanel jpThongTin1;
    private javax.swing.JLabel lbCCCD;
    private javax.swing.JLabel lbCCCD1;
    private javax.swing.JLabel lbChuongTrinh;
    private javax.swing.JLabel lbDay;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbKhoa;
    private javax.swing.JLabel lbLop;
    private javax.swing.JLabel lbNganh;
    private javax.swing.JLabel lbNoiSinh;
    private javax.swing.JLabel lbQuocTich;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JTextField tfCCCD;
    private javax.swing.JTextField tfChuongTrinh;
    private javax.swing.JTextField tfDanToc;
    private javax.swing.JTextField tfDay;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGioiTinh;
    private javax.swing.JTextField tfKhoa;
    private javax.swing.JTextField tfNganh;
    private javax.swing.JTextField tfNoiSinh;
    private javax.swing.JTextField tfQuocTich;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfTen;
    // End of variables declaration//GEN-END:variables
}
