/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demoOOPStudentManagement.view;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hientruongthmh
 */
public class TeacherManagementStateUI extends javax.swing.JFrame {

    /**
     * Creates new form TeacherManagementStateUI
     */
    public TeacherManagementStateUI() {
        initComponents();    
        String[] columns = {"Số Thứ Tự", "Mã Lớp", "Chuyên Ngành", "Tên Lớp", "Số Lượng Sinh Viên"};
        Object[][] data = {
            {1, "CS101", "Công Nghệ Thông Tin", "Lập Trình Java", 30},
            {2, "MATH101", "Toán Học", "Giải Tích 1", 25},
            {3, "ENG101", "Ngôn Ngữ", "Tiếng Anh Cơ Bản", 40},
            {4, "PHY101", "Vật Lý", "Cơ Học", 35},
            {5, "CHEM101", "Hóa Học", "Hóa Học Đại Cương", 20}
        };

        model_TableDSLop = new DefaultTableModel(data, columns);
        tbDSlop.setModel(model_TableDSLop);
        
        ListSelectionModel modelSelected = tbDSlop.getSelectionModel();
        
        modelSelected.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        modelSelected.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        
        });
        
    }
    
    /*
    tbDSlop.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tbDSlop.getSelectedRow();
                    if (selectedRow >= 0) {
                        // Lấy các giá trị từ các cột trong bảng khi chọn một lớp
                        int stt = (int) tbDSlop.getValueAt(selectedRow, 0); // Số Thứ Tự
                        String classID = (String) tbDSlop.getValueAt(selectedRow, 1); // Mã Lớp
                        String major = (String) tbDSlop.getValueAt(selectedRow, 2); // Chuyên Ngành
                        String className = (String) tbDSlop.getValueAt(selectedRow, 3); // Tên Lớp
                        int studentCount = (int) tbDSlop.getValueAt(selectedRow, 4); // Số Lượng Sinh Viên

                        // Mở TeacherManagement_ClassStateUI với các thông tin lớp học
                        openClassDetails(stt, classID, major, className, studentCount);
                    }
                }
            }
        });
       */
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SPDSlop = new javax.swing.JScrollPane();
        tbDSlop = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        SPTKB = new javax.swing.JScrollPane();
        tbThoiKhoaBieu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách lớp học"));

        tbDSlop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã lớp", "Chuyên ngành", "Tên lớp học", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SPDSlop.setViewportView(tbDSlop);
        if (tbDSlop.getColumnModel().getColumnCount() > 0) {
            tbDSlop.getColumnModel().getColumn(0).setResizable(false);
            tbDSlop.getColumnModel().getColumn(1).setResizable(false);
            tbDSlop.getColumnModel().getColumn(2).setResizable(false);
            tbDSlop.getColumnModel().getColumn(3).setResizable(false);
            tbDSlop.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPDSlop, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(SPDSlop, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời khoá biểu"));

        tbThoiKhoaBieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên C.Ng", "Tên lớp", "Phòng học", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SPTKB.setViewportView(tbThoiKhoaBieu);
        if (tbThoiKhoaBieu.getColumnModel().getColumnCount() > 0) {
            tbThoiKhoaBieu.getColumnModel().getColumn(0).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(1).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(2).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(3).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(4).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(5).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(6).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(7).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(8).setResizable(false);
            tbThoiKhoaBieu.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPTKB)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(SPTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn phúc khảo"));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherManagementStateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherManagementStateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherManagementStateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherManagementStateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherManagementStateUI().setVisible(true);
            }
        });
    }
    
    //Tự thêm
    public DefaultTableModel model_TableDSLop;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SPDSlop;
    private javax.swing.JScrollPane SPTKB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable tbDSlop;
    private javax.swing.JTable tbThoiKhoaBieu;
    // End of variables declaration//GEN-END:variables

    private void openClassDetails(int serialNumber, String classCode, String department, String className, int studentCount) {
    // Truyền các thông tin vào TeacherManagement_ClassStateUI
        TeacherManagement_ClassStateUI classUI = new TeacherManagement_ClassStateUI(serialNumber, classCode, department, className, studentCount);
        classUI.setVisible(true);
        this.setVisible(false); // Ẩn TeacherManagementStateUI nếu không muốn mở song song
    }
}
